on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  job-development:
    runs-on: ubuntu-latest
    steps:
     - uses: .github/workflows/run-bicep-apim-with-env.yaml
       with:
         environmentType: Development
       env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}

  job-production:
    runs-on: ubuntu-latest
    steps:
     - uses: .github/workflows/run-bicep-apim-with-env.yaml
       with:
         environmentType: Production
       env:
         AZURE_CREDENTIALS: ${{ secrets.AZURE_CLIENT_ID }}
         AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
         API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}
      
