on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  job-development:
    uses: ./.github/workflows/run-bicep-apim-with-env.yml
    with:
      environmentType: Development
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}

  job-production:
    uses: ./.github/workflows/run-bicep-apim-with-env.yml
    with:
      environmentType: Production
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}
    
      ##AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PRODUCTION }}
      ##AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ##AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      